(function(g){var window=this;var s9=function(a,b,c,d){var e=b.Kb();g.oe(a.element,"ytp-suggestion-set",!!e.videoId);var h=b.jh();d=b.Oc(c,d?d:"mqdefault.jpg");var k=b instanceof g.KB?g.Rk(b.lengthSeconds):null,m=!!h,h=m&&"RD"==g.bE(h).type;c={title:b.title,author:b.author,author_and_views:e.shortViewCount?b.author+" \u2022 "+e.shortViewCount:b.author,watch:g.P("YTP_WATCH_VIDEO_OR_PLAYLIST",{TITLE:b.title},b.title),duration:k,url:b.Mj(c),is_featured:e.Cs,is_list:m,is_mix:h,background:d?"background-image: url("+d+")":""};b instanceof
g.eE&&(c.playlist_length=b.A);a.update(c)},t9=function(a){var b=g.T(a),c=b.experiments.Z("video_wall_moving_thumbnails_autoplay"),d=b.experiments.Z("video_wall_moving_thumbnails_hover"),c=c||d;
this.B=b.B&&!b.C;b=g.Ji||g.Cc?{style:"will-change: opacity"}:null;d={I:"img",U:"ytp-videowall-moving-thumbnail",T:{src:"{{moving_thumbnail}}"}};g.R.call(this,{I:"a",U:"ytp-videowall-still",T:{href:"{{url}}",target:this.B?"_blank":null,"aria-label":"{{watch}}","data-is-featured":"{{is_featured}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},P:[{I:"div",U:"ytp-videowall-still-image",T:{style:"{{background}}"}},c?d:null,{I:"span",U:"ytp-videowall-still-featured-label",P:[g.P("YTP_FEATURED")]},
{I:"span",U:"ytp-videowall-still-info",P:[{I:"span",U:"ytp-videowall-still-info-bg",P:[{I:"span",U:"ytp-videowall-still-info-content",T:b,P:[{I:"span",U:"ytp-videowall-still-info-title",P:["{{title}}"]},{I:"span",U:"ytp-videowall-still-info-author",P:["{{author_and_views}}"]},{I:"span",U:"ytp-videowall-still-info-duration",P:["{{duration}}"]}]}]}]},{I:"span",fa:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],P:[{I:"span",U:"ytp-videowall-still-listlabel-icon"},g.P("YTP_PLAYLIST"),
{I:"span",U:"ytp-videowall-still-listlabel-length",P:[" (",{I:"span",P:["{{playlist_length}}"]},")"]}]},{I:"span",fa:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],P:[{I:"span",U:"ytp-videowall-still-listlabel-mix-icon"},g.P("YTP_MIX"),{I:"span",U:"ytp-videowall-still-listlabel-length",P:[" (50+)"]}]}]});this.g=a;this.o=null;this.N("click",this.EK);this.N("keypress",this.FK);c&&this.R(this.sa["ytp-videowall-moving-thumbnail"],"load",this.HK);g.T(a).experiments.Z("player_interaction_logging")&&
(a=a.app.ca,g.ob(a.B,this),b=String(a.F++),this.element.setAttribute("data-visual-id",b),g.Mb(this,(0,g.z)(a.D,a,this)))},u9=function(a){if(5E5<g.Sw(a.g.app.ia)){var b=a.o.Gj();
b&&a.update({moving_thumbnail:b})}},v9=function(a){g.nE.call(this,a,{I:"div",
fa:["ytp-thumbnail-overlay","ytp-channel-overlay"],P:[{I:"div",U:"ytp-thumbnail-overlay-image",T:{style:"{{background}}"}},{I:"div",U:"ytp-thumbnail-overlay-curtain"}]})},w9=function(a){var b=g.T(a).experiments.Z("moving_thumbnails_autonav"),c={I:"img",
U:"ytp-upnext-moving-thumbnail",T:{src:"{{moving_thumbnail}}"}},c={I:"div",U:"ytp-upnext",T:{"aria-label":"{{watch}}"},P:[{I:"div",U:"ytp-thumbnail-overlay-image",T:{style:"{{background}}"}},b?c:null,{I:"div",U:"ytp-thumbnail-overlay-curtain"},{I:"span",U:"ytp-upnext-top",P:[{I:"span",U:"ytp-upnext-header",P:[g.P("YTP_PLAYLIST_UP_NEXT")]},{I:"span",U:"ytp-upnext-title",P:["{{title}}"]},{I:"span",U:"ytp-upnext-author",P:["{{author}}"]}]},{I:"a",U:"ytp-upnext-autoplay-icon",T:{href:"{{url}}"},P:[{I:"svg",
T:{height:"100%",version:"1.1",viewBox:"0 0 98 98",width:"100%"},P:[{I:"circle",U:"ytp-svg-autoplay-circle",T:{cx:"49",cy:"49",fill:"#000","fill-opacity":"0.8",r:"48"}},{I:"circle",U:"ytp-svg-autoplay-ring",T:{cx:"-49",cy:"49","fill-opacity":"0",r:"46.5",stroke:"#FFFFFF","stroke-dasharray":"293","stroke-dashoffset":"-293","stroke-width":"4",transform:"rotate(-90)"}},{I:"polygon",U:"ytp-svg-autoplay-triangle",T:{fill:"#fff",points:"32,27 72,49 32,71"}}]}]},{I:"span",U:"ytp-upnext-bottom",P:[{I:"span",
U:"ytp-upnext-cancel"},{I:"span",U:"ytp-upnext-paused",P:[g.P("YTP_AUTOPLAY_PAUSED_2")]}]},{I:"span",U:"ytp-upnext-close"}]};g.R.call(this,c);this.B=null;var d=this.sa["ytp-upnext-cancel"],c=this.sa["ytp-upnext-close"];this.B=new g.R({I:"button",fa:["ytp-upnext-cancel-button","ytp-button"],T:{tabindex:0,"aria-label":g.P("YTP_AUTOPLAY_CANCEL")},P:[g.P("YTP_CANCEL")]});g.J(this,this.B);this.B.N("click",this.kt,this);this.B.Ba(d);d=new g.R({I:"button",fa:["ytp-upnext-close-button","ytp-button"]});g.J(this,
d);d.N("click",this.kt,this);d.Ba(c);this.g=a;this.H=this.sa["ytp-svg-autoplay-ring"];this.D=this.A=this.o=this.C=null;this.F=new g.ee(this.tj,5E3,this);g.J(this,this.F);this.G=0;this.R(this.sa["ytp-upnext-autoplay-icon"],"click",this.RF);this.jt();this.R(a,"autonavvisibility",this.jt);b&&this.R(this.sa["ytp-upnext-moving-thumbnail"],"load",this.jM)},hva=function(a,b){a.C=b;
s9(a,b,g.T(a.g),"hqdefault.jpg");g.me(a.element,"ytp-moving-thumbnail-loaded");a.update({moving_thumbnail:"data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7"});5E5<g.Sw(a.g.app.ia)&&(b=a.C.Gj())&&a.update({moving_thumbnail:b})},x9=function(a){a.o||(g.zl("a11y-announce",g.P("YTP_PLAYLIST_UP_NEXT")+" "+a.C.title),a.G=(0,g.pk)(),a.o=new g.ee(a.Gl,25,a),a.Gl());
g.me(a.element,"ytp-upnext-autoplay-paused")},z9=function(a){y9(a);
a.G=(0,g.pk)();a.Gl();g.M(a.element,"ytp-upnext-autoplay-paused")},y9=function(a){a.o&&(a.o.dispose(),a.o=null)},A9=function(a,b){g.lE.call(this,{I:"div",
fa:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.g=a;this.L=!1},B9=function(a){a=g.T(a);
return a.Yd&&!a.ma},C9=function(a,b){A9.call(this,a,"videowall-endscreen");
this.ba=a;this.$=b;this.F=0;this.o=[];this.G=this.C=this.B=null;this.H=this.V=!1;this.D=new g.tn(this);g.J(this,this.D);this.K=new g.ee(g.qa(g.M,this.element,"ytp-show-tiles"),0);g.J(this,this.K);b=new g.R({I:"button",fa:["ytp-button","ytp-endscreen-previous"],T:{"aria-label":g.P("YTP_PREVIOUS")},P:[{I:"svg",T:{height:"100%",version:"1.1",viewBox:"0 0 32 32",width:"100%"},P:[{I:"path",T:{d:"M 19.41,20.09 14.83,15.5 19.41,10.91 18,9.5 l -6,6 6,6 z",fill:"#fff"}}]}]});g.J(this,b);b.Ba(this.element);
b.N("click",this.jE,this);this.J=new g.Jk({I:"div",U:"ytp-endscreen-content"});g.J(this,this.J);this.J.Ba(this.element);b=new g.R({I:"button",fa:["ytp-button","ytp-endscreen-next"],T:{"aria-label":g.P("YTP_NEXT")},P:[{I:"svg",T:{height:"100%",version:"1.1",viewBox:"0 0 32 32",width:"100%"},P:[{I:"path",T:{d:"m 12.59,20.34 4.58,-4.59 -4.58,-4.59 1.41,-1.41 6,6 -6,6 z",fill:"#fff"}}]}]});g.J(this,b);b.Ba(this.element);b.N("click",this.CK,this);this.A=new w9(a);g.J(this,this.A);g.us(this.g,this.A.element,
4);this.ua()},D9=function(a){return(0,g.S)(a.H,function(a){return g.mE(a)})},E9=function(a,b,c){return 0==b&&a.B.length&&(b=c/C9.b,2<=c/C9.b&&2<=b&&g.T(a.g).experiments.Z("video_wall_emphasize_first"))?2*C9.b:C9.b},F9=function(a){var b=a.$.Uo();
b!=a.V&&(a.V=b,a.g.Va("autonavvisibility"))},G9=function(a){A9.call(this,a,"subscribecard-endscreen");
var b=a.getVideoData();this.o=new v9(a);g.J(this,this.o);g.us(this.g,this.o.element,4);this.A=new g.R(["div","ytp-subscribe-card",["img","ytp-author-image",{src:b.profilePicture}],["div","ytp-subscribe-card-right",["div","ytp-author-name",b.author],["div","html5-subscribe-button-container"]]]);g.J(this,this.A);this.A.Ba(this.element);this.B=new g.Gs(g.P("YTP_SUBSCRIBE"),g.P("YTP_UNSUBSCRIBE"),!0,b.Op,b.subscribed,"trailer-endscreen",a);g.J(this,this.B);this.B.Ba(this.A.sa["html5-subscribe-button-container"]);
this.ua()},H9=function(a){g.Pm.call(this,a);
g.vi({});this.g=null;this.isAvailable=!0;this.o=new g.tn(this);g.J(this,this.o);this.A=g.T(a);B9(a)?this.g=new C9(this.b,this):this.A.ma?this.g=new G9(this.b):this.g=new A9(this.b);g.J(this,this.g);g.us(this.b,this.g.element,4);this.tu();this.o.R(a,"videodatachange",this.tu,this);this.o.R(a,"crn_endscreen",this.pK,this);this.o.R(a,"crx_endscreen",this.qK,this)};
g.A(t9,g.R);g.f=t9.prototype;g.f.qf=function(){var a=this.o.Kb().videoId;g.U7(this.g.app,a,this.o.Sc,this.o.jh(),void 0,void 0)};
g.f.EK=function(a){g.ED(this.g,this);g.Ul(a,this.g,!this.g.isFullscreen()&&this.B,this.o.Sc)&&this.qf()};
g.f.GK=function(){this.ya(this.A);this.A=null;u9(this)};
g.f.FK=function(a){switch(a.keyCode){case 13:case 32:g.Bj(a)||(this.qf(),g.Aj(a))}};
g.f.HK=function(a){120<g.wj(a).naturalWidth&&g.M(this.element,"ytp-videowall-moving-thumbnail-loaded")};
g.A(v9,g.nE);v9.prototype.qb=function(a){a?this.A.show():g.Lr(this.A)};
g.A(w9,g.R);g.f=w9.prototype;g.f.tj=function(){this.A&&(this.F.stop(),this.ya(this.D),this.D=null,this.A.close(),this.A=null)};
g.f.jt=function(){this.qb(g.lD(this.g))};
g.f.HF=function(){window.focus();this.tj()};
g.f.Gl=function(){var a=g.T(this.g).experiments.b("autoplay_time")||1E4,b=Math.min((0,g.pk)()-this.G,a),a=Math.min(b/a,1);this.H.setAttribute("stroke-dashoffset",-293*(a+1));1<=a?this.select(!0):this.o&&this.o.start()};
g.f.select=function(a){var b=g.T(this.g);if(b.experiments.Z("autonav_notifications")&&a&&window.Notification&&window.document.hasFocus){var c=window.Notification.permission;g.Fr(this.g,"xwebnotifications",{permission:c});"default"==c?window.Notification.requestPermission():"granted"!=c||window.document.hasFocus()||(c=this.C.Kb(),this.tj(),this.A=new window.Notification(g.P("YTP_PLAYLIST_UP_NEXT"),{body:c.title,icon:c.Oc(b)}),this.D=this.R(this.A,"click",this.HF),this.F.start())}y9(this);this.g.Ii(!1,
a)};
g.f.RF=function(a){!g.Tf(this.B.element,g.wj(a))&&g.Ul(a,this.g)&&this.select()};
g.f.kt=function(){g.vD(this.g,"autonavcancel");g.nD(this.g,!0)};
g.f.jM=function(a){120<g.wj(a).naturalWidth&&g.M(this.element,"ytp-moving-thumbnail-loaded")};
g.f.S=function(){y9(this);this.tj();w9.M.S.call(this)};
g.A(A9,g.lE);A9.prototype.create=function(){this.L=!0};
A9.prototype.destroy=function(){this.L=!1};
A9.prototype.Ml=function(){return!1};
g.A(C9,A9);C9.b=2;g.f=C9.prototype;g.f.create=function(){C9.M.create.call(this);var a=this.g.getVideoData();a&&(this.B=D9(a),this.C=a);this.Bf();this.D.R(this.g,"appresize",this.Bf);this.D.R(this.g,"videodatachange",this.DK);this.D.R(this.g,"autonavchange",this.jw);this.D.R(this.g,"autonavcancel",this.BK);this.D.R(this.element,"transitionend",this.XG)};
g.f.destroy=function(){g.vn(this.D);g.Ob(this.o);this.o=[];this.B=null;C9.M.destroy.call(this);g.me(this.element,"ytp-show-tiles");this.K.stop()};
g.f.Ml=function(){return 1!=this.C.autonavState};
g.f.ni=function(){return g.DD(this.g)&&this.Ml()&&!this.G};
g.f.show=function(){C9.M.show.call(this);g.me(this.element,"ytp-show-tiles");g.T(this.g).isMobile?g.fe(this.K):this.K.start();(this.H||this.G&&this.G!=this.C.clientPlaybackNonce)&&g.nD(this.g,!1);var a=this.ni();g.DD(this.g)&&g.T(this.g).experiments.Z("ui_logging")&&this.$.log({cancelButtonShow:a?"1":"0",state:this.Ml()?"enabled":"disabled"});a?(F9(this),2==this.C.autonavState?g.T(this.g).experiments.Z("fast_autonav_in_background")&&3==this.g.Wv()?this.A.select(!0):x9(this.A):3==this.C.autonavState&&
z9(this.A)):(g.nD(this.g,!0),F9(this))};
g.f.ua=function(){C9.M.ua.call(this);z9(this.A);F9(this)};
g.f.XG=function(a){g.wj(a)==this.element&&this.Bf()};
g.f.Bf=function(){if(this.B&&this.B.length){var a=g.T(this.g).experiments.Z("video_wall_moving_thumbnails_hover");g.M(this.element,"ytp-endscreen-paginate");for(var b=g.kn(this.element),c=b.width/b.height,d=96/54,e=C9.b,h=C9.b,k=Math.max(b.width/96,2),m=Math.max(b.height/54,2),l=this.B.length,p=Math.pow(C9.b,2),t=l*p,u=E9(this,0,m),y=E9(this,1,m),t=t+(Math.pow(u,2)-p),t=t+(Math.pow(y,2)-p),t=t-p;0<t&&(e<k||h<m);){var H=e/C9.b,E=h/C9.b,L=e<=k-C9.b&&t>=E*p,ma=h<=m-C9.b&&t>=H*p;if((H+1)/E*d/c>c/(H/(E+
1)*d)&&ma)t-=H*p,h+=C9.b;else if(L)t-=E*p,e+=C9.b;else if(ma)t-=H*p,h+=C9.b;else break}d=!1;k=C9.b+u;t>=3*p&&6>=l*p-t&&(h>=k||e>=k)&&y<=C9.b&&(d=!0);t=96*e;p=54*h;c=t/p<c?b.height/p:b.width/t;c=Math.min(c,2);t*=c;p*=c;t*=g.cf(b.width/t||1,1,1.21);p*=g.cf(b.height/p||1,1,1.21);t=Math.floor(Math.min(b.width,t));p=Math.floor(Math.min(b.height,p));b=this.J.element;g.jn(b,t,p);g.Tm(b,{marginLeft:t/-2+"px",marginTop:p/-2+"px"});hva(this.A,this.B[0]);g.oe(this.element,"ytp-endscreen-takeover",this.ni());
F9(this);c=t+4;t=p+4;p=0;k=!this.ni();m=!1;for(H=0;H<e;H++)for(E=0;E<h;E++)if(L=y>C9.b&&1<=p&&!m?p+1:p,ma=0,d&&H>=e-C9.b&&E>=h-C9.b?ma=1:0==E%C9.b&&0==H%C9.b&&(E<u&&H<u?0==E&&0==H&&(ma=u):y>C9.b&&E>=h-y&&H>=e-y?E==h-y&&H==e-y&&(m=!0,L=1,ma=y):ma=C9.b),L=(L+this.F)%l,L=0>L*l?L+l:L,0!=ma){var ya=this.o[p];ya||(ya=new t9(this.g),this.o[p]=ya,b.appendChild(ya.element));var Ja=Math.floor(t*E/h),$a=Math.floor(c*H/e),he=Math.floor(t*(E+ma)/h)-Ja-4,wd=Math.floor(c*(H+ma)/e)-$a-4;g.Zm(ya.element,$a,Ja);g.jn(ya.element,
wd,he);g.Tm(ya.element,"transitionDelay",(E+H)/20+"s");g.oe(ya.element,"ytp-videowall-still-mini",1==ma);g.oe(ya.element,"ytp-videowall-still-large",2<ma);ma=ya;L=this.B[L];ya=k&&!a;ma.o=L;Ja=g.T(ma.g);s9(ma,L,Ja,g.je(ma.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg");g.me(ma.element,"ytp-videowall-moving-thumbnail-loaded");ma.update({moving_thumbnail:"data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7"});ya?(g.M(ma.element,"ytp-videowall-active"),
u9(ma)):Ja.experiments.Z("video_wall_moving_thumbnails_hover")&&!ma.A&&(ma.A=ma.N("mouseover",ma.GK));Ja=L.Sc;ya=ma.g;L=ma;Ja=Ja&&Ja.itct;g.T(ya).experiments.Z("player_interaction_logging")&&(ma=ya.app.ca,ya=Ja,L=L.element.getAttribute("data-visual-id"),g.FD(ma,"onLogServerVeCreated",{id:L,tracking_params:ya}));p++}g.oe(this.element,"ytp-endscreen-paginate",p<l);for(a=this.o.length-1;a>=p;a--)ya=this.o[a],g.Lf(ya.element),g.Nb(ya);this.o.length=p}};
C9.o=2;C9.g=1.21;g.f=C9.prototype;g.f.DK=function(){var a=this.g.getVideoData();this.C!=a&&(this.F=0,this.B=D9(a),this.C=a,this.Bf())};
g.f.CK=function(){this.F+=this.o.length;this.Bf()};
g.f.jE=function(){this.F-=this.o.length;this.Bf()};
g.f.JC=function(){return!!this.A.o};
g.f.jw=function(a){1==a?(this.H=!1,this.G=this.C.clientPlaybackNonce,y9(this.A),this.b&&this.Bf()):(this.H=!0,this.b&&this.ni()&&(2==a?x9(this.A):3==a&&z9(this.A)))};
g.f.BK=function(a){if(a){for(a=0;a<this.o.length;a++)g.GD(this.ba,this.o[a],!0);this.jw(1)}else this.G=null,this.H=!1;this.Bf()};
g.A(G9,A9);G9.prototype.show=function(){G9.M.show.call(this);this.o.qb(!0)};
G9.prototype.ua=function(){G9.M.ua.call(this);this.o.qb(!1)};
g.A(H9,g.Pm);g.f=H9.prototype;g.f.hw=function(){var a=this.b.getVideoData(),b=!B9(this.b)||!(!a.H||!a.H.length),a=g.Nm(a,"ypc_module"),c=g.F4(this.b.app);return(b||!1)&&!a&&!c};
g.f.Uo=function(){return(this.g instanceof C9||!1)&&this.g.b&&this.g.ni()};
g.f.HC=function(){return this.Uo()?this.g.JC():!1};
g.f.S=function(){g.ej(this.b,"endscreen");H9.M.S.call(this)};
g.f.load=function(){H9.M.load.call(this);this.g.show();g.T(this.b).ma&&.01>Math.random()&&this.log({trailerEndscreenShow:1})};
g.f.log=function(a){g.Fr(this.b,"end",a)};
g.f.unload=function(){H9.M.unload.call(this);this.g.ua();this.g.destroy();this.isAvailable=!1};
g.f.pK=function(a){this.hw()&&(this.g.L||this.g.create(),"load"==a.getId()&&this.load())};
g.f.qK=function(a){"load"==a.getId()&&this.loaded&&this.unload()};
g.f.tu=function(){g.ej(this.b,"endscreen");var a=Math.max(1E3*(this.b.getVideoData().lengthSeconds-10),0),a=new g.aj(a,0x8000000000000,{id:"preload",namespace:"endscreen"}),b=new g.aj(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});this.b.sb([a,b])};
window._exportCheck==g.ta&&g.aa("ytmod.player.endscreen",H9,void 0);})(_yt_player);
